name: 'Setup Python Poetry'
description: 'Setup python and poetry.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - shell: bash
      run: pip install poetry
    - shell: bash
      run: poetry install